### PR TITLE
added restaurant button to navigation bar

### PR DESCRIPTION
**Pull request by nala-he**
Please review, provide feedback, and approve (at least two approvals) or deny the request. Thank you!

### CODE REVIEW

**Comment by bovornc** [comment]
looks good! :)

**Comment by MaceeQi** [comment]
agreed!

**Review by t1yena — APPROVED** [review]
restaurant button looks good!

**Comment by t1yena** [comment]
restaurant button looks good!

**Review by bovornc — APPROVED** [review]

**Pull request merged**
