### PR TITLE
Integration4 t6 f2 34 login/signup

### PR DESCRIPTION
**Pull request by nala-he**
Users can sign up as any one types of users and be directed to the profile page. Business user can access to business profile by clicking business profile page in the user profile page. Critic user can write review in restaurant homepage.

Am and I went to professor's OH today and solved the infinite loop issues. Now everything should behave nicely.

Currently, there is one bug from the critic review feature that I cannot solve. When user submit the review, the business home page went blank. If you refresh the page, the new critic review will show up in the list, but the user at the same time got kicked out from login status. Could you please take a look at it if you got a chance? Something must be wrong in review-list, business-home, or create-review files. I compared the codes with the webdev creating tuit code, but cannot spot what is going wrong. I cannot go to the OH tomorrow morning, but if we are still stuck by the end of tomorrow, I will go to OH on Friday.

### CODE REVIEW

**Comment by bovornc** [comment]
Signup feature isn't working for me, and neither is login after trying the test users' credentials in the database.

**Comment by nala-he** [comment]
> Signup feature isn't working for me, and neither is login after trying the test users' credentials in the database.

Oh, that's weird. I tried multiple users from database and was able to login. Also able to sign up. For example, try username "christopher" and password "christopher123"

**Comment by nala-he** [comment]
> Users can sign up as any one types of users and be directed to the profile page. Business user can access to business profile by clicking business profile page in the user profile page. Critic user can write review in restaurant homepage.
> 
> Am and I went to professor's OH today and solved the infinite loop issues. Now everything should behave nicely.
> 
> Currently, there is one bug from the critic review feature that I cannot solve. When user submit the review, the business home page went blank. If you refresh the page, the new critic review will show up in the list, but the user at the same time got kicked out from login status. Could you please take a look at it if you got a chance? Something must be wrong in review-list, business-home, or create-review files. I compared the codes with the webdev creating tuit code, but cannot spot what is going wrong. I cannot go to the OH tomorrow morning, but if we are still stuck by the end of tomorrow, I will go to OH on Friday.

Solved the create review issues. All features should be able to work after user login/signup.

**Comment by t1yena** [comment]
The login/signup works well for me! Thank you yutong :)
A few things I noticed:
- I am still getting the create review issue when I submit a review the review doesn't show up right away. I have to refresh the page to show it but at that point I am logged out. This might be something Am might have to check!
- A business user is allowed to create duplicate business profiles when the create business profile button is clicked multiple times.
- I think we should be redirected to the edit business page or given some sort of alert once the create profile button is clicked. It's hard to tell that the business profile has been created because the button doesn't redirect the user to a new page.

**Comment by MaceeQi** [comment]
Hi Yutong - thank you for setting this up! I agree with Yena's points above and also noticed a few other things:

1) In the profile page, I think it would be better if there was "@" in front of the user's username since that's how we've been indicating the handle, and removing the "@" in front of the user type because it looks like the handle is @USERTYPE rather than their actual handle.

2) Since we did not implement the functionality for editing a user's profile, should we just remove the edit profile button?

3) When first signing up as a business user and then being directed to the profile page, if I click on the Business Profile Page link in the profile, it will take me to /profile/business but it's showing me the contents of the last business profile that was created by another business user. For example, I was logged in as business user that created Olive Garden restaurant. After logging out and signing up as new business user and clicking on Business Profile link (before creating an actual Business Profile), it's showing me edit info for Olive Garden. But that might just be residual because then the server crashes with this error "CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "RestaurantModel"". If I log out and try clicking on that link again, nothing shows but still crashes server so I think showing the last restaurant was just a residual effect or something. Once that happens, I don't think I'm able to create any business page for that profile again because clicking on create business profile afterwards keeps crashing.

4) I am having trouble signing up as an average user. It only works after I change the type field to a different field (business or critic) and then changing back to average. If I just leave it as default (average) or even if I open drop down and only click on average, I cannot signup as an average user - it crashes the server saying a type is required.

**Comment by nala-he** [comment]
> Hi Yutong - thank you for setting this up! I agree with Yena's points above and also noticed a few other things:
> 
> 1. In the profile page, I think it would be better if there was "@" in front of the user's username since that's how we've been indicating the handle, and removing the "@" in front of the user type because it looks like the handle is @usertype rather than their actual handle.
> 2. Since we did not implement the functionality for editing a user's profile, should we just remove the edit profile button?
> 3. When first signing up as a business user and then being directed to the profile page, if I click on the Business Profile Page link in the profile, it will take me to /profile/business but it's showing me the contents of the last business profile that was created by another business user. For example, I was logged in as business user that created Olive Garden restaurant. After logging out and signing up as new business user and clicking on Business Profile link (before creating an actual Business Profile), it's showing me edit info for Olive Garden. But that might just be residual because then the server crashes with this error "CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "RestaurantModel"". If I log out and try clicking on that link again, nothing shows but still crashes server so I think showing the last restaurant was just a residual effect or something. Once that happens, I don't think I'm able to create any business page for that profile again because clicking on create business profile afterwards keeps crashing.
> 4. I am having trouble signing up as an average user. It only works after I change the type field to a different field (business or critic) and then changing back to average. If I just leave it as default (average) or even if I open drop down and only click on average, I cannot signup as an average user - it crashes the server saying a type is required.

Solved 1, 2, 3, 4.

**Comment by nala-he** [comment]
> The login/signup works well for me! Thank you yutong :) A few things I noticed:
> 
> * I am still getting the create review issue when I submit a review the review doesn't show up right away. I have to refresh the page to show it but at that point I am logged out. This might be something Am might have to check!
> * A business user is allowed to create duplicate business profiles when the create business profile button is clicked multiple times.
> * I think we should be redirected to the edit business page or given some sort of alert once the create profile button is clicked. It's hard to tell that the business profile has been created because the button doesn't redirect the user to a new page.

fixed 2 and 3. gonna work on 1

**Comment by nala-he** [comment]
All issues solved. Please let me know if it works on your end too. Thank you!

**Review by bovornc — APPROVED** [review]
Everything works well on my end. No crashes/bugs/infinite loops!

**Comment by nala-he** [comment]
> Everything works well on my end. No crashes/bugs/infinite loops!

Great!!! I am going to cry... Spent the whole day to debug >U< So glad it is working.

**Comment by t1yena** [comment]
everything works on my end as well!! thank you so much yutong :)

**Review by t1yena — APPROVED** [review]

**Comment by nala-he** [comment]
> everything works on my end as well!! thank you so much yutong :)

Great! Thank you!

**Comment by MaceeQi** [comment]
Thanks so much for making the updates, Yutong! Everything regarding log in/sign up worked on my part. A couple small things I noticed is that when I sign up as a critic and leave a comment on a newly created restaurant/restaurant with no reviews yet, the page goes blank and in the console I get the following error: "TypeError: Cannot read properties of undefined (reading '_id')" in the ReviewList component. Another detail that I didn't realize until now is that there's no way to edit the restaurant's price so all new restaurants will always have a price of "price". Let me know if you need any help with these!

**Comment by bovornc** [comment]
I tried it out and was getting that same bug that Macee was getting. According to console.log debugging it seems like when a review is created for a restaurant that currently has no reviews, the array for that restaurant's reviews in review-list.js goes from an empty array to an array with 1 "undefined" item (for whatever reason), which causes the crash when the page tries to get the review._id from that undefined object.

**Comment by nala-he** [comment]
> I tried it out and was getting that same bug that Macee was getting. According to console.log debugging it seems like when a review is created for a restaurant that currently has no reviews, the array for that restaurant's reviews in review-list.js goes from an empty array to an array with 1 "undefined" item (for whatever reason), which causes the crash when the page tries to get the review._id from that undefined object.

Thank you Am for fixing it!!

**Comment by nala-he** [comment]
> Thanks so much for making the updates, Yutong! Everything regarding log in/sign up worked on my part. A couple small things I noticed is that when I sign up as a critic and leave a comment on a newly created restaurant/restaurant with no reviews yet, the page goes blank and in the console I get the following error: "TypeError: Cannot read properties of undefined (reading '_id')" in the ReviewList component. Another detail that I didn't realize until now is that there's no way to edit the restaurant's price so all new restaurants will always have a price of "price". Let me know if you need any help with these!

Thank you! I added the price edit feature.

**Pull request merged**
