### PR TITLE
Integration3 t6 f2 94 restaurant search

### PR DESCRIPTION
**Pull request by MaceeQi**
Implemented restaurant search functionality. Navigating to restaurants tab will display all restaurants in the database in alphabetical order. Once you search for a restaurant, will show you restaurants with matching name. Clicking on the restaurant will take you to the business profile

### CODE REVIEW

**Comment by bovornc** [comment]
Only works if the search bar input matches a restaurant's name exactly (case sensitive), and crashes the node server if we click the search button without typing anything into the search bar.

**Comment by MaceeQi** [comment]
Fixed the error handling for empty/blank searches. For searching, it is supposed to only find the restaurant if the name matches exactly - I've tried searching by partial matches using regex but have not had any success yet

**Review by bovornc — APPROVED** [review]
Works great!

**Review by nala-he — APPROVED** [review]
Works well after the revision!

**Pull request merged**
