### PR TITLE
Integration3 t6f2 93 reviews connect frontend backend

### PR DESCRIPTION
**Pull request by bovornc**
Obviously missing stuff regarding login features, so anyone can edit or delete any review. Will need to add the feature that lets the "edit" button on reviews show/hide the updateReview box, but as of right now everything should be working fine.

### CODE REVIEW

**Review by nala-he — CHANGES_REQUESTED** [review]
Hi Am, it works well! A few suggestions: 
1. Could you please make the newly added review to the top of the list. To achieve that, you just need to change "push" into "unshift" in the review-reducer createReviewThunk.fulfilled. 
2. If you have time, do you mind adding a default avatar image to the public/images and let the user without an avatar use our default avatar? 
3. What does the pen+note icon do below the exit button? If we do not allow the reviewer to edit their review, we may just remove that button.
Thank you!!

**Comment by bovornc** [comment]
The "unshift" solution wasn't working for some reason, but having review-list map the reviews in reverse order got the desired result.
The "edit" button doesn't have a function right now, but the plan was to make it show/hide the "update review" part of the review when the user clicked on it, IF that review's critic ID matched the user's ID.

**Review by MaceeQi — APPROVED** [review]
Tried it out - works great!

**Review by nala-he — APPROVED** [review]

**Comment by nala-he** [comment]
Thank you Am for the revisions!! It looks great!

**Comment by t1yena** [comment]
Works well on my end as well! I think we are good to merge this

**Review by t1yena — APPROVED** [review]

**Pull request merged**
