### PR TITLE
Integration2 t6 f2 75 edit profile reducers

### PR DESCRIPTION
**Pull request by t1yena**

### CODE REVIEW

**Comment by nala-he** [comment]
I encountered two issues when I ran the edit business profile locally: 
1. After deleting one or more featured items and adding one new featured item, the list went back to the original featured item list without saving the new changes. However, just adding featured items worked as expected.
2. After typing in new account info and restaurant info without clicking saving, when I continue to add a new update and click "Add update", the page refreshed and all changes including the newly added update could not be saved. 

I can help debugging after I finish all my controllers today.

**Review by MaceeQi — CHANGES_REQUESTED** [review]
I ran it locally but for some reason am unable to either add a new featured item or add an update. I tried imitating it again and I think this is what is happening: when I first start up the application and navigate to localhost:3000/profile/business/123 (Red Lobster) and click edit, I'm taken to http://localhost:3000/#/profile/business/123/edit. If the first thing I do is add a new update, the page refreshes and the URL changes to http://localhost:3000/?popularItem=on&popularItem=on#/profile/business/123/edit. The new update that I tried adding is not added but after the refresh, when I add the update again, then it successfully adds. 

Similarly, if the first thing I do is add a new featured item without the popular item checked, the same thing happens - page refreshes, url changes, and featured item is not added. But subsequent adds to featured item w/o the popular check seems to be added. However, if I try adding a featured item w/ the popular item check, the page refreshes again and all the featured items that I had added before are no longer there and the item I just tried adding is not added. I am then only able to add one featured item with popular item checked and any other type of feature item added thereafter (checked or unchecked) do not seem to get added and it also gets rid of the featured items I tried adding before. So there are also times when I cannot add any featured items at all. Not sure what is going on

**Comment by t1yena** [comment]
thanks for the feedback guys! I think I fixed the bugs, please give it another try

**Review by nala-he — APPROVED** [review]
I tested the revised version and it worked well on my end. Thank you!

**Review by MaceeQi — APPROVED** [review]
Worked well on my end as well - thanks for the changes!

**Pull request merged**
