### PR TITLE
Integration3 t6 f2 92 rest info feature

### PR DESCRIPTION
**Pull request by nala-he**
User can access a restaurant by clicking restaurant button, view the listed restaurant (I will update the search restaurant part by merging Macee's feature branch later), click the restaurant to view the details (You may see a blank page, to "wake it up", commented out or back line 43 in business-home.js, click the terminal window to make it update the change, then you will see the page. This is definitely not the right way to solve the issue, but I cannot figure out other solutions. I will go to OH to fix it. I think after we implement user login/signup, this issue will be solved automatically.)

Business owner can view the restaurant profile page by clicking profile, adding /business/:actualRestaurantIdFromDatabase to the URL path after /profile. You may see a blank page, to "wake it up", commented out or back line 29 in business-profile.js, click the terminal window to make it update the change, then you will see the page. You can then view the page, edit, and save the updated profile's basic info and featured items. The changes will be shown in our remote database. We do not use the Hours data collection anymore. The daily open hours are added to restaurant collections (monday, tuesday, ... sunday).

### CODE REVIEW

**Comment by nala-he** [comment]
The updated version including Am's reviews feature and Macee's search restaurant feature.

**Comment by t1yena** [comment]
it works on my end! :) The only thing as you already mentioned is that we have to "wake up" the console. I can look into debugging this as well! I will try to make it to office hours as well. Do you think we should have default values for the restaurant pic and banner? I did add an empty banner pic in the react images on my pull request just in case we would want it!

**Comment by nala-he** [comment]
> it works on my end! :) The only thing as you already mentioned is that we have to "wake up" the console. I can look into debugging this as well! I will try to make it to office hours as well. Do you think we should have default values for the restaurant pic and banner? I did add an empty banner pic in the react images on my pull request just in case we would want it!

Thank you! Yes, I think it would be great to have default values for the restaurant pic and banner! :)

**Review by MaceeQi — COMMENTED** [review]
Just tried it out - works well besides the points you mentioned of needing to comment/uncomment out the lines of code. Let me know if you need help with that! Also happy to look into it

**Review by bovornc — APPROVED** [review]
Cloned it and everything works fine, outside of the aforementioned "waking up the console" issue.

**Review by MaceeQi — APPROVED** [review]
Works great now! :)

**Pull request merged**
